Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 2048]
    vbox.customize ["modifyvm", :id, "--cpus", 1]
  end
  
  config.vm.provision "shell", inline: "echo Hello World from $(hostname)"
  
  config.vm.define "server1" do |server1|
    server1.vm.hostname = "server1"
    server1.vm.network "private_network", ip: "192.168.10.101"
    server1.vm.provider "virtualbox" do |vbox|
      vbox.name = "server1"
    end
  end

  config.vm.define "server2" do |server2|
    server2.vm.hostname = "server2"
    server2.vm.network "private_network", ip: "192.168.10.102"
    server2.vm.provider "virtualbox" do |vbox|
      vbox.name = "server2"
    end
  end

  config.vm.define "server3" do |server3|
    server3.vm.hostname = "server3"
    server3.vm.network "private_network", ip: "192.168.10.103"
    server3.vm.provider "virtualbox" do |vbox|
      vbox.name = "server3"
    end
  end
end
