Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos7vm"
  config.vm.network "private_network", ip: "192.168.10.101"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "centos7"
    vbox.memory = 2048
    vbox.cpus = 1
  end
end
