#Build in serial
ENV["VAGRANT_NO_PARALLEL"] = "yes"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

#  config.vm.provider "virtualbox" do |vbox|
#    vbox.customize ["modifyvm", :id, "--memory", 2048]
#    vbox.customize ["modifyvm", :id, "--cpus", 1]
#  end
  
  config.vm.provision "shell",
    inline: "echo Hello World from $(hostname)"
  config.vm.provision "shell",
    path: "bootstrap.sh"
  
  (1..3).each do|i|
    config.vm.define "server#{i}" do |server|
      server.vm.hostname = "server#{i}"
      server.vm.network "private_network", ip: "192.168.10.10#{i}"
      server.vm.provider "virtualbox" do |vbox|
        vbox.name = "server#{i}"
        vbox.cpus=1
        vbox.memory=2048
      end
    end
  end
end
