Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "server1"
  config.vm.define "server2"

  # Run Ansible from the Vagrant Host

  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.playbook = "provisioning/playbook.yml"
  end
end